// <auto-generated />
namespace SitioTaxis_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MuchoMuchos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MuchoMuchos));
        
        string IMigrationMetadata.Id
        {
            get { return "202305100037514_MuchoMuchos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
